# Generated by Django 4.1.5 on 2023-01-18 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='yayimlanma_tarihi',
            field=models.DateTimeField(),
        ),
    ]
