# Generated by Django 4.1.5 on 2023-01-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0003_remove_makale_aktif'),
    ]

    operations = [
        migrations.AddField(
            model_name='makale',
            name='aktif',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
