# Generated by Django 4.1.5 on 2023-01-19 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0006_gazeteci_alter_makale_yazar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gazeteci',
            name='biyografi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
