# Generated by Django 4.1.5 on 2023-01-19 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0007_alter_gazeteci_biyografi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='yaratilma_tarihi',
            field=models.DateField(auto_now_add=True),
        ),
    ]
