# Generated by Django 4.1.5 on 2023-01-19 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haberler', '0008_alter_makale_yaratilma_tarihi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='makale',
            name='yaratilma_tarihi',
            field=models.DateField(auto_now=True),
        ),
    ]
